databases:
  - name: negasonic
    databaseName: negasonic
    user: negasonic

services:
  - type: web
    name: negasonic
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: negasonic
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
